import type { ExportInput, ExportResult, MemoryData } from "../types.js";

const HEADER = "<!-- Generated by AIHub. Do not edit — source: aihub server -->\n\n";

function buildContent(input: ExportInput): string {
  const parts: string[] = [];

  // Global rules
  if (input.globalRules.length > 0) {
    for (const r of input.globalRules) {
      parts.push(r.content, "");
    }
  }

  // Project rules
  if (input.rules.length > 0) {
    for (const r of input.rules) {
      parts.push(r.content, "");
    }
  }

  // Global context
  if (input.globalContext.length > 0) {
    for (const c of input.globalContext) {
      parts.push(c.content, "");
    }
  }

  // Project context
  if (input.context.length > 0) {
    for (const c of input.context) {
      parts.push(c.content, "");
    }
  }

  // Memories
  if (input.memories.length > 0) {
    parts.push("## Known Context (from previous sessions)\n");
    for (const m of input.memories) {
      const tags = parseTags(m.tags);
      const tagStr = tags.length > 0 ? ` [${tags.join(", ")}]` : "";
      parts.push(`- ${m.content}${tagStr}`);
    }
    parts.push("");
  }

  // Handoff
  if (input.handoff) {
    parts.push("## Previous Agent Handoff\n", input.handoff, "");
  }

  return parts.join("\n");
}

function parseTags(tags: string | string[]): string[] {
  if (Array.isArray(tags)) return tags;
  try { return JSON.parse(tags); } catch { return []; }
}

// ─── Claude ──────────────────────

export function exportClaude(input: ExportInput): ExportResult {
  return {
    files: [{ path: "CLAUDE.md", content: HEADER + buildContent(input) }],
  };
}

// ─── Codex ───────────────────────

export function exportCodex(input: ExportInput): ExportResult {
  return {
    files: [{ path: "AGENTS.md", content: HEADER + buildContent(input) }],
  };
}

// ─── Cursor ──────────────────────

export function exportCursor(input: ExportInput): ExportResult {
  return {
    files: [{ path: ".cursorrules", content: HEADER + buildContent(input) }],
  };
}

// ─── Copilot ─────────────────────

export function exportCopilot(input: ExportInput): ExportResult {
  return {
    files: [{ path: ".github/copilot-instructions.md", content: HEADER + buildContent(input) }],
  };
}

// ─── Windsurf ────────────────────

export function exportWindsurf(input: ExportInput): ExportResult {
  return {
    files: [{ path: ".windsurfrules", content: HEADER + buildContent(input) }],
  };
}

// ─── Registry ────────────────────

export function exportForAgent(agent: string, input: ExportInput): ExportResult {
  switch (agent) {
    case "claude":
    case "claude-internal":
      return exportClaude(input);
    case "codebuddy":
      return exportClaude(input); // CodeBuddy uses same format as Claude
    case "codex": return exportCodex(input);
    case "cursor": return exportCursor(input);
    case "copilot": return exportCopilot(input);
    case "windsurf": return exportWindsurf(input);
    default: throw new Error(`Unknown agent: ${agent}`);
  }
}
